name: Feature request
description: Suggest an improvement to Dekui.
title: "[Feature]: "
body:
  - type: textarea
    id: problem
    attributes:
      label: What would this improve?
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested behavior
    validations:
      required: true
